apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: jpaezr/product-service-v1:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: db-config
